### PR TITLE
Add error messages for 268503 and 268404

### PR DESCRIPTION
**Pull request by Peter0x44**

### CODE REVIEW

**Comment by Mkwiiripper** [comment]
Cool😎😎

**Comment by Peter0x44** [comment]
Oops, the title for the pr is incorrect, but the commit itself is fine

**Comment by Artuto** [comment]
The commit is actualy wrong too lol

**Review by Artuto — APPROVED** [review]
lgtm

**Comment by Peter0x44** [comment]
Oof, don't know how that happened, I'll be more careful next time

**Pull request merged**
