### PR TITLE
Quick DNS command update

### PR DESCRIPTION
**Pull request by 2secslater**
- Swap the Cloudflare and Google DNS server IP addresses, being more ethical.
- Mention what to do if ISPs block use of external custom DNS servers.

### CODE REVIEW

**Review by Artuto — CHANGES_REQUESTED** [review]
We've had reports of 1.1.1.1 not working always; so 8.8.8.8 is prefered.

**Comment by 2secslater** [comment]
Ah alrighty, I'll revert it for ya

**Review by Artuto — APPROVED** [review]
lgtm

**Comment by larsenv** [comment]
Thanks, I was just thinking earlier about how we should update the !dns command for that.

**Pull request merged**
