### PR TITLE
Ignore eclipse files

### PR DESCRIPTION
**Pull request by Gamebuster19901**
Adds .gitignore entries for the Eclipse IDE, so they aren't pushed to the repo.

### CODE REVIEW

**Comment by Peter0x44** [comment]
why are you opening 3 separate prs, especially when one of them is literally for a single character

**Comment by Gamebuster19901** [comment]
> why are you opening 3 separate prs, especially when one of them is literally for a single character

A PR should be focused on one issue. I identified 3 issues:

1. .gitignore was missing for eclipse files
2. the license was incorrect
3. there were formatting issues in some source files

**Comment by larsenv** [comment]
I agree

**Comment by Artuto** [comment]
I mean I dont use Eclipse so...

**Comment by Gamebuster19901** [comment]
This will be bundled with the next update.

**Pull request closed without merging**
