### PR TITLE
Updated DNS.java

### PR DESCRIPTION
**Pull request by yeah-its-gloria**
Added Wiimmfi DNS for wiimmfi stuff

### CODE REVIEW

**Comment by Artuto** [comment]
This doesnt even compiles.

**Comment by yeah-its-gloria** [comment]
then make it compiling

**Comment by Artuto** [comment]
Your code doesnt works

**Comment by yeah-its-gloria** [comment]
then make it working

**Comment by Artuto** [comment]
Its a Pull Request, **you** are the responsible for it.

**Pull request closed without merging**
