### PR TITLE
Added two notes to error codes.

### PR DESCRIPTION
**Pull request by KcrPL**
> Added two notes for error codes and that is:
* 105409 - If you are getting this problem while doing something with Wii Mail - check if you patched nwc24msg.cfg correctly.
* 20103 - Delete NWC_AUTHDATA file stored in nand:/shared2/. Delete it using WiiXplorer.

Might come in handy :)

### CODE REVIEW

**Comment by spotlightishere** [comment]
a moment of silence for those who have manual modifications to the file. wee this'll be fun

**Comment by KcrPL** [comment]
:D

**Comment by spotlightishere** [comment]
done, in the future please create an issue adding mentioned errors

**Comment by KcrPL** [comment]
I think it's just faster to make an PR, don't ya think :P

**Comment by spotlightishere** [comment]
```
---
local_codes:
  # Hi from Spotlight!
  # Please don't edit this file directly, as it causes
  # chaos with other things.
```

**Pull request merged**
