### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by yeah-its-gloria**
- Removed emotes to make the guide more serious.
- Added Links to JDA and Discordrb.
- Modded existing Links.

### CODE REVIEW

**Comment by Artuto** [comment]
Not sure about the links

**Comment by yeah-its-gloria** [comment]
i can remove them if you want

**Review by Artuto — CHANGES_REQUESTED** [review]
Remove links. Maybe add a used libs section.

**Comment by yeah-its-gloria** [comment]
Okay, will do that now.

**Comment by yeah-its-gloria** [comment]
Removed links. Moved link to JDA to the bottom.

**Comment by yeah-its-gloria** [comment]
@Artuto is the File okay now?

**Review by Artuto — APPROVED** [review]

**Pull request merged**
